export type PickupZone = "CUN" | "RM" | "TULUM" | "PA";

export const pickupZoneLabel: Record<PickupZone, { es: string; en: string }> = {
  CUN: { es: "Cancún", en: "Cancún" },
  RM: { es: "Riviera Maya", en: "Riviera Maya" },
  TULUM: { es: "Tulum", en: "Tulum" },
  PA: { es: "Puerto Aventuras", en: "Puerto Aventuras" },
};

export type PickupPoint = {
  zone: PickupZone;
  name: string;
};

// Importado de hotelsa_actualizacion_sistema.xlsx. Para agregar/editar hoteles,
// solo edita este array y súbelo — no requiere tocar ningún otro archivo.
export const pickupPoints: PickupPoint[] = [
  { zone: "CUN", name: "RIU DUNAMAR" },
  { zone: "CUN", name: "RIU PALACE COSTA MUJERES" },
  { zone: "CUN", name: "ALLURE COSTA MUJERES" },
  { zone: "CUN", name: "SECRETS PLAYA BLANCA" },
  { zone: "CUN", name: "PLANET HOLLYWOOD" },
  { zone: "CUN", name: "CATALONIA GRAND COSTA MUJERES" },
  { zone: "CUN", name: "MAJESTIC ELEGANCE COSTA MUJERES" },
  { zone: "CUN", name: "MAJESTIC MIRAGE COSTA MUJERES" },
  { zone: "CUN", name: "RIU LATINO COSTA MUJERES" },
  { zone: "CUN", name: "TRS PALLADIUM COSTA MUJERES" },
  { zone: "CUN", name: "GRAND PALLADIUM COSTA MUJERES" },
  { zone: "CUN", name: "TRS CORAL HOTEL" },
  { zone: "CUN", name: "SECRETS PLAYA MUJERES" },
  { zone: "CUN", name: "ATELIER PLAYA MUJERES" },
  { zone: "CUN", name: "DREAMS PLAYA MUJERES" },
  { zone: "CUN", name: "FINEST PLAYA MUJERES" },
  { zone: "CUN", name: "SLS PLAYA MUJERES" },
  { zone: "CUN", name: "EXCELLENCE PLAYA MUJERES" },
  { zone: "CUN", name: "BELOVED PLAYA MUJERES" },
  { zone: "CUN", name: "VILLAS DEL PALMAR" },
  { zone: "CUN", name: "GARZA BLANCA - CUN" },
  { zone: "CUN", name: "ALL RITMO CANCUN" },
  { zone: "CUN", name: "ULTRA MAR PUERTO JUAREZ(OXXO) / ISLA MUJERES" },
  { zone: "CUN", name: "AMARA CANCUN BEACHFRONT" },
  { zone: "CUN", name: "LUXURY OCEANFRONT AMARA" },
  { zone: "CUN", name: "DREAMS VISTA CANCUN" },
  { zone: "CUN", name: "KM,0 GO MART CANCUN" },
  { zone: "CUN", name: "RENAISSANCE CANCUN" },
  { zone: "CUN", name: "HOTEL BONAMPAK (MEETING POINT PARA CUN CENTRO)" },
  { zone: "CUN", name: "KRYSTAL URBAN CENTRO" },
  { zone: "CUN", name: "OASIS BY SMART" },
  { zone: "CUN", name: "WYNDHAM GARDEN CANCUN DOWTOWN CANCUN" },
  { zone: "CUN", name: "HOTEL IBIS- CUN" },
  { zone: "CUN", name: "PLAZA MADEIRA" },
  { zone: "CUN", name: "CITY EXPRESS BY MARRIOTT CANCUN" },
  { zone: "CUN", name: "OFICINAS BEST DAY CANCUN" },
  { zone: "CUN", name: "COURTYARD BY MARRIOTT HOTEL CANCUN" },
  { zone: "CUN", name: "FOUR POINTS CUN" },
  { zone: "CUN", name: "HAMPTON INN CUMBRES" },
  { zone: "CUN", name: "FAIRFIELD INN & SUITES CANCUN AIRPORT" },
  { zone: "CUN", name: "IMPERIAL LAS PERLAS" },
  { zone: "CUN", name: "OCEAN VIEW ARENAS // HOLIDAY INN ARENAS" },
  { zone: "CUN", name: "CANCUN BAY RESORT" },
  { zone: "CUN", name: "TEMPTATION RESORT" },
  { zone: "CUN", name: "OCEAN SPA HOTEL" },
  { zone: "CUN", name: "AQUA MARINA BEACH" },
  { zone: "CUN", name: "OCCIDENTAL / BARCELO COSTA CANCUN" },
  { zone: "CUN", name: "SOTAVENTO" },
  { zone: "CUN", name: "CALYPSO CANCUN" },
  { zone: "CUN", name: "GRAND OASIS PALM BEACH // ZENS" },
  { zone: "CUN", name: "CLUB INTERNATIONAL THE ROYAL CANCUN" },
  { zone: "CUN", name: "BREATHLESS CANCUN SOUL" },
  { zone: "CUN", name: "REAL INN CANCUN" },
  { zone: "CUN", name: "CASA MAYA" },
  { zone: "CUN", name: "RIU CARIBE" },
  { zone: "CUN", name: "RIU PALACE PENINSULA" },
  { zone: "CUN", name: "MAYA CARIBE CELUISMA" },
  { zone: "CUN", name: "SUNSET MARINA RESORT & YACHT CLUB" },
  { zone: "CUN", name: "DOS PLAYAS-CUN" },
  { zone: "CUN", name: "GRAND ROYAL LAGOON" },
  { zone: "CUN", name: "PARADERO POK-TA-POK -CUN" },
  { zone: "CUN", name: "LAGUNA SUITES CANCUN" },
  { zone: "CUN", name: "PRESIDENTE INTERCONTINENTAL" },
  { zone: "CUN", name: "HOLIDAY INN POK TA POK" },
  { zone: "CUN", name: "BEACHSCAPE KIN HA" },
  { zone: "CUN", name: "DREAMS SANDS CANCUN" },
  { zone: "CUN", name: "FIESTA AMERICANA VC" },
  { zone: "CUN", name: "RIU PALACE LAS AMERICAS" },
  { zone: "CUN", name: "RIU CANCUN" },
  { zone: "CUN", name: "LA PALMA BEACHFRONT HOTEL & CLUB NAUTICO - CANCUN" },
  { zone: "CUN", name: "FIESTA AMERICANA GRAND CORAL BEACH (PICK UP EN LA ARCADA)" },
  { zone: "CUN", name: "HYATT ZIVA CANCUN" },
  { zone: "CUN", name: "ALOFT CANCUN" },
  { zone: "CUN", name: "HYATT ZIVA RIVIERA CANCUN(ANTES SECRETS SILVERSANDS)" },
  { zone: "CUN", name: "KRYSTAL GRAND//REFLECT KRYSTAL/KRYSTAL GRAND PUNTA CANCUN/ KRYSTAL ALTITUD" },
  { zone: "CUN", name: "KRYSTAL CANCUN" },
  { zone: "CUN", name: "SELINA CANCUN" },
  { zone: "CUN", name: "COCO BONGO CANCUN" },
  { zone: "CUN", name: "SALVIA CONDOMINIOS" },
  { zone: "CUN", name: "CARISA Y PALMA// CITA CASETA DE SEGURIDAD" },
  { zone: "CUN", name: "MAYAN MONKEY CANCUN" },
  { zone: "CUN", name: "OCEAN DREAM" },
  { zone: "CUN", name: "ROYALTON CHIC SUITES CANCUN" },
  { zone: "CUN", name: "ROYAL SUNSET // SUNSET ROYAL BEACH" },
  { zone: "CUN", name: "LE BLANC" },
  { zone: "CUN", name: "GRAND PARK ROYAL // CANCUN CARIBE PARK ROYAL" },
  { zone: "CUN", name: "SUNSCAPE CANCUN(ANTES WYNDHAM ALLTRA CANCUN)" },
  { zone: "CUN", name: "HYATT ZILARA CANCUN" },
  { zone: "CUN", name: "FLAMINGO" },
  { zone: "CUN", name: "NYX CANCUN / AVALON GRAND" },
  { zone: "CUN", name: "BEACH PALACE" },
  { zone: "CUN", name: "MELODY MAKER" },
  { zone: "CUN", name: "CANOPY BY HILTON" },
  { zone: "CUN", name: "PARK ROYAL BEACH // PARK ROYAL PIRAMIDES" },
  { zone: "CUN", name: "WESTIN LAGUNA MAR" },
  { zone: "CUN", name: "LIVE AQUA" },
  { zone: "CUN", name: "RIU PALACE KUKULKAN // RIU KUKULKAN" },
  { zone: "CUN", name: "VILLAS MARLIN" },
  { zone: "CUN", name: "OCCIDENTAL / BARCELO TUCANCUN BEACH" },
  { zone: "CUN", name: "CASA TURQUESA" },
  { zone: "CUN", name: "THE ROYAL SANDS" },
  { zone: "CUN", name: "KEMPINSKI HOTEL CANCUN // THE RITZ CARLTON" },
  { zone: "CUN", name: "GOLDEN PARNASSUS" },
  { zone: "CUN", name: "SANDOS CANCUN" },
  { zone: "CUN", name: "SECRETS THE VINE CANCUN" },
  { zone: "CUN", name: "HARD ROCK CANCUN HOTEL" },
  { zone: "CUN", name: "J.W. MARRIOTT" },
  { zone: "CUN", name: "MARRIOTT CASA MAGNA" },
  { zone: "CUN", name: "MARRIOT CANCUN RESORT" },
  { zone: "CUN", name: "PARADISSUS CANCUN" },
  { zone: "CUN", name: "FIESTA AMERICANA CONDESA" },
  { zone: "CUN", name: "GRAND OASIS CANCUN // THE PYRAMID GRAND OASIS (PICK UP EN LAS ESCALERAS)" },
  { zone: "CUN", name: "WYNDHAM GRAND CANCUN ( ANTES OMNI CANCUN)" },
  { zone: "CUN", name: "EMPORIO CANCUN" },
  { zone: "CUN", name: "HILTON CANCUN MAR CARIBE-CUN (ANTES THE ROYAL UNO)" },
  { zone: "CUN", name: "THE ROYAL ISLANDER" },
  { zone: "CUN", name: "SEADUST CANCUN" },
  { zone: "CUN", name: "IBEROSTAR CANCUN GOLF & SPA // CORAL LEVEL AT IBEROSTAR SELECTION CANCUN" },
  { zone: "CUN", name: "HYATT VIVID GRAND ISLAND" },
  { zone: "CUN", name: "RIU VENTURA" },
  { zone: "CUN", name: "CROWN PARADISE CLUB" },
  { zone: "CUN", name: "GR SOLARIS" },
  { zone: "CUN", name: "SECRETS MIRABEL CANCUN RESORT // NOW ESMERALD CANCUN" },
  { zone: "CUN", name: "SOLYMAR" },
  { zone: "CUN", name: "CONDOMINIOS BRISAS" },
  { zone: "CUN", name: "ROYAL SOLARIS" },
  { zone: "CUN", name: "GR CARIBE" },
  { zone: "CUN", name: "CANCUN PLAZA // B SEA CANCUN PLAZA" },
  { zone: "CUN", name: "HOTEL CYAN RESORT & SPA // BEL AIR COLLECTION" },
  { zone: "CUN", name: "OLEO CANCUN" },
  { zone: "CUN", name: "SUN PALACE" },
  { zone: "CUN", name: "WESTIN REGINA // CLUB REGINA" },
  { zone: "CUN", name: "WESTIN RESORT SPA CUN" },
  { zone: "CUN", name: "NIZUC CANCUN" },
  { zone: "CUN", name: "CLUB MED CANCUN" },
  { zone: "CUN", name: "RESIDENCENCE INN CANCUN" },
  { zone: "CUN", name: "AKUAZUL RESORT" },
  { zone: "CUN", name: "AVA RESORT CANCUN" },
  { zone: "CUN", name: "AEROPUERTO CANcun" },
  { zone: "CUN", name: "GO MART IRUN HUAYACAN" },
  { zone: "CUN", name: "HILTON GARDEN INN CANCUN AIRPORT" },
  { zone: "CUN", name: "HYATT PLACE AIRPORT" },
  { zone: "CUN", name: "CITY EXPRESS PLUS BY MARRIOTT CANCUN" },
  { zone: "CUN", name: "AVANI CANCUN AIRPOT" },
  { zone: "CUN", name: "MOON PALACE NIZUC PALAPA" },
  { zone: "CUN", name: "MOON PALACE SUNRISE ARENAS" },
  { zone: "CUN", name: "MOON PALACE GRAND" },
  { zone: "CUN", name: "HAVEN RIVIERA CANCUN" },
  { zone: "CUN", name: "HILTON CANCUN RIVIERA" },
  { zone: "CUN", name: "CITY EXPRESS PLUS CUN AEROPUERTO" },
  { zone: "CUN", name: "WALDORF ASTORIA CANCUN" },
  { zone: "CUN", name: "ROYALTON RIVIERA" },
  { zone: "CUN", name: "DREAMS NATURA" },
  { zone: "CUN", name: "ROYALTON SPLASH" },
  { zone: "CUN", name: "SENSIRA RESORTS & SPA RIVIERA MAYA" },
  { zone: "CUN", name: "ZOETRY PARAISO LA BONITA" },
  { zone: "CUN", name: "MARGARITA VILLE CANCUN (VIEJO)" },
  { zone: "CUN", name: "DESIRE RIVIERA MAYA RESORT - PETEMPICH" },
  { zone: "CUN", name: "BREATHLESS RIVIERA (PETEMPICH)" },
  { zone: "CUN", name: "SECRETS RIVIERA CANCUN" },
  { zone: "CUN", name: "MARGARITA VILLE RIVIERA (NUEVO)" },
  { zone: "CUN", name: "IBEROSTAR SELECTION RIVIERA CUN (ANTES PALMAR BEACH PETEMPICH) // AZUL BEACH" },
  { zone: "CUN", name: "DREAMS PUERTO MORELOS (ANTES HYATT ZIVA RIVIERA PETEMPICH)" },
  { zone: "CUN", name: "H10 OCEAN CORAL & TURQUESA" },
  { zone: "CUN", name: "DREAMS SAPHIRE // NOW SAPPHIRE" },
  { zone: "CUN", name: "EXCELLENCE RIVIERA" },
  { zone: "CUN", name: "DREAMS RIVIERA" },
  { zone: "CUN", name: "DESIRE RIVIERA MAYA PEARL RESORT - PTO. MORELOS" },
  { zone: "CUN", name: "THE FIVES OCEAN FRONT" },
  { zone: "CUN", name: "PARROQUIA SAN JOSE OBREO PTO MORELOS" },
  { zone: "CUN", name: "LETRAS DE PUERTO MORELOS" },
  { zone: "CUN", name: "MARINA EL CID (LOBBY EL CID)" },
  { zone: "CUN", name: "MARINA EL CID (LOBBY VENTUS)" },
  { zone: "CUN", name: "DREAMS JADE ( ANTES NOW JADE RIVIERA)" },
  { zone: "CUN", name: "GRAND RESIDENCES" },
  { zone: "CUN", name: "HACIENDA MORELOS PTO MORELOS" },
  { zone: "CUN", name: "ZOETRY VILLA ROLANDI PETEMPRICH" },
  { zone: "CUN", name: "ACAMA REEF" },
  { zone: "CUN", name: "PUERTO MORELOS" },
  { zone: "CUN", name: "OCEAN REEF" },
  { zone: "CUN", name: "GENERATION" },
  { zone: "RM", name: "NICKELODEON" },
  { zone: "RM", name: "DORADO ROYALE" },
  { zone: "RM", name: "DORADO ROYAL" },
  { zone: "RM", name: "HOTEL BOUTIQUE" },
  { zone: "RM", name: "VALENTIN IMPERIAL" },
  { zone: "RM", name: "VIDANTA MAYAN PALACE" },
  { zone: "RM", name: "SENSES RIVIERA MAYA // ARTISAN" },
  { zone: "RM", name: "IBEROSTAR PARAISO DEL MAR" },
  { zone: "RM", name: "IBEROSTAR PARAISO BEACH" },
  { zone: "RM", name: "IBEROSTAR PARAISO LINDO" },
  { zone: "RM", name: "IBEROSTAR JOIA PARAISO (LOBBY GRAND)" },
  { zone: "RM", name: "IBEROSTAR PARAISO MAYA" },
  { zone: "RM", name: "BELMONT MAROMA RESORT & SPA" },
  { zone: "RM", name: "SECRETS MAROMA BEACH" },
  { zone: "RM", name: "CATALONIA PLAYA MAROMA" },
  { zone: "RM", name: "KANAI-RM" },
  { zone: "RM", name: "DORADO MAROMA" },
  { zone: "RM", name: "HACIENDA TRES RIOS" },
  { zone: "RM", name: "BLUE BAY GRAND ESMERALDA" },
  { zone: "RM", name: "H10 OCEAN MAYA" },
  { zone: "RM", name: "HYATT ZILARA RM ( ANTES SECRETS CAPRI)" },
  { zone: "RM", name: "BLUE DIAMOND (MANDARIN ORIENTAL)" },
  { zone: "RM", name: "MAYACOBA-LOBBY ANDAZ" },
  { zone: "RM", name: "ROSEWOOD MAYAKOBA" },
  { zone: "RM", name: "BANYAN TREE MAYAKOBA" },
  { zone: "RM", name: "FAIRMONT MAYAKOBA" },
  { zone: "RM", name: "GRAND VELAS (LOBBY AMBASSADOR)" },
  { zone: "RM", name: "GRAND VELAS LOBBY ZENT" },
  { zone: "RM", name: "GRAND VELAS (LOBBY GRAND CLASS)" },
  { zone: "RM", name: "PRINCESS RIVIERA" },
  { zone: "RM", name: "PRINCESS SUNSET" },
  { zone: "RM", name: "PRINCES PLATINUM YUCATAN" },
  { zone: "RM", name: "OCEAN RIVIERA PARADISE" },
  { zone: "RM", name: "THE FIVES BEACH // AZUL FIVES" },
  { zone: "RM", name: "PETIT LAFITTE" },
  { zone: "RM", name: "VICEROY RIVIERA MAYA" },
  { zone: "RM", name: "LEREVE" },
  { zone: "RM", name: "PRIVANZA DEL MAR" },
  { zone: "RM", name: "SELVAMAR" },
  { zone: "RM", name: "SANDOS CARACOL" },
  { zone: "RM", name: "SECRETS MOXCHE" },
  { zone: "RM", name: "THE ROYAL HACIENDAS" },
  { zone: "RM", name: "MAREAZUL" },
  { zone: "RM", name: "PARADISUS ESMERALDA" },
  { zone: "RM", name: "PARADISUS LA PERLA" },
  { zone: "RM", name: "REEF COCO BEACH" },
  { zone: "RM", name: "OFICINA COBA SUNSET" },
  { zone: "RM", name: "ELEMENTS" },
  { zone: "RM", name: "MAHEKAL BEACH RESORT" },
  { zone: "RM", name: "BODEGUITA DEL MEDIO - PLAYA" },
  { zone: "RM", name: "LIVE AQUA RM" },
  { zone: "RM", name: "YUCATAN RESORT PDC" },
  { zone: "RM", name: "REEF 28" },
  { zone: "RM", name: "DEVOSSION LIVE AQUA PDC (ANTES GRAND HYATT PLAYA - RM)" },
  { zone: "RM", name: "FIESTA INN PDC" },
  { zone: "RM", name: "HYATT VIVID PDC (ANTES HILTON PDC)" },
  { zone: "RM", name: "WYNDHAM ALLTRA PDC" },
  { zone: "RM", name: "HM PLAYA DEL CARMEN" },
  { zone: "RM", name: "PLAZA LAS PERLAS" },
  { zone: "RM", name: "COCO BONGO (MEETING POINT)" },
  { zone: "RM", name: "TUKAN HOTEL PLAYA DEL CARMEN" },
  { zone: "RM", name: "MAYA VILLA CONDO HOTEL & BEACHCLUB" },
  { zone: "RM", name: "HACIENDA DEL CARIBE" },
  { zone: "RM", name: "MAGIC BLUE" },
  { zone: "RM", name: "THE FIVE DOWNTOWN" },
  { zone: "RM", name: "THE PALM AT PLAYA" },
  { zone: "RM", name: "SR. FROGS ENTRADA PRINCIPAL" },
  { zone: "RM", name: "PLAYACAR PALACE" },
  { zone: "RM", name: "VIVA WYNDHAM GARDEN" },
  { zone: "RM", name: "OFICINAS DE EXPEDIA - RIVIERA" },
  { zone: "RM", name: "GOMART COLOSIO(RUTA MAYA)" },
  { zone: "RM", name: "KOOX PLAYA DEL CARMEN" },
  { zone: "RM", name: "CITY EXPRESS" },
  { zone: "RM", name: "CENTRO MAYA" },
  { zone: "RM", name: "LIVERPOOL" },
  { zone: "RM", name: "STARBUCKS DE CENTRO MAYA" },
  { zone: "RM", name: "RESIDENCE INN PDC" },
  { zone: "RM", name: "RIU LUPITA" },
  { zone: "RM", name: "PALMAIA" },
  { zone: "RM", name: "SANDOS PLAYACAR" },
  { zone: "RM", name: "IBEROSTAR TUCAN" },
  { zone: "RM", name: "IBEROSTAR QUETZAL" },
  { zone: "RM", name: "RIU YUCATAN" },
  { zone: "RM", name: "RIU PALACE MEXICO" },
  { zone: "RM", name: "RIU TEQUILA" },
  { zone: "RM", name: "VIVA WYNDHAM MAYA" },
  { zone: "RM", name: "RIU PLAYACAR" },
  { zone: "RM", name: "PLAZA PLAYACAR - RM" },
  { zone: "RM", name: "OCCIDENTAL ROYAL HIDEAWAY" },
  { zone: "RM", name: "OCCIDENTAL ALLEGRO PLAYACAR" },
  { zone: "RM", name: "VIVA WYNDHAM AZTECA" },
  { zone: "RM", name: "RIU PALACE RIVIERA MAYA" },
  { zone: "RM", name: "REEF PLAYACAR" },
  { zone: "RM", name: "FISHERMAN PLAYACAR // ROYAL SUNSET FISHERMENS RESORT & SPA" },
  { zone: "RM", name: "HACIENDA VISTA PAKAL" },
  { zone: "RM", name: "BAHIA DEL ESPIRITU SANTO PLAYACAR" },
  { zone: "RM", name: "HARD ROCK CAMPO DE GOLF PLAYACAR" },
  { zone: "RM", name: "HOTEL CASA KAOBA" },
  { zone: "RM", name: "XCARET MEXICO - RM" },
  { zone: "RM", name: "XCARET ARTE" },
  { zone: "RM", name: "OCCIDENTAL XCARET ANTES FLAMENCO XCARET" },
  { zone: "RM", name: "PAAMUL HOTEL RIVIERA" },
  { zone: "RM", name: "HARD ROCK HOTEL HACIENDA (SOUTH LOBBY) // LOBBY ROJO" },
  { zone: "RM", name: "HARD ROCK HOTEL HEAVEN (NORTH LOBBY) // LOBBY AZUL" },
  { zone: "PA", name: "CHEDRAUI PUERTO AVENTURAS" },
  { zone: "PA", name: "OMNI PUERTO AVENTURAS BEACH R." },
  { zone: "PA", name: "DREAMS PTO. AVENTURAS" },
  { zone: "PA", name: "DOLPHIN DISCOVERY PTO AVENTURAS" },
  { zone: "RM", name: "CATALONIA RIVIERA MAYA" },
  { zone: "RM", name: "CATALONIA YUCATAN" },
  { zone: "RM", name: "BARCELO CARIBE" },
  { zone: "RM", name: "BARCELO MAYA BEACH" },
  { zone: "RM", name: "BARCELO MAYA RIVIERA" },
  { zone: "RM", name: "BARCELO COLONIAL" },
  { zone: "RM", name: "BARCELO TROPICAL" },
  { zone: "RM", name: "BARCELO MAYA PALACE" },
  { zone: "RM", name: "BEL AIR COLLECTION XPU-HA RIV. MAYA" },
  { zone: "TULUM", name: "CATALONIA ROYAL TULUM" },
  { zone: "RM", name: "DORADO SEASIDE// LOBBY PALMS" },
  { zone: "RM", name: "HIDDEN BEACH RM" },
  { zone: "RM", name: "DORADO SEASIDE SUITES" },
  { zone: "RM", name: "UNICO" },
  { zone: "RM", name: "PALLADIUM COLONIAL" },
  { zone: "RM", name: "PALLADIUM KANTENAH" },
  { zone: "RM", name: "PALLADIUM RIVIERA" },
  { zone: "RM", name: "PALLADIUM WHITESAND" },
  { zone: "RM", name: "TRS YUCATAN BY PALLADIUM" },
  { zone: "RM", name: "GRAND SIRENIS" },
  { zone: "RM", name: "LAS CASITAS AKUMAL" },
  { zone: "RM", name: "CLUB AKUMAL CARIBE & VILLA MAYA" },
  { zone: "RM", name: "PARADERO AKUMAL" },
  { zone: "RM", name: "AKUMAL BAY" },
  { zone: "RM", name: "SECRETS AKUMAL" },
  { zone: "RM", name: "VILLAS AKUMAL" },
  { zone: "TULUM", name: "GRAND OASIS RIVIERA ANTES GRAND OASIS TULUM // SUNSCAPE AKUMAL" },
  { zone: "TULUM", name: "BAHIA PRINCIPE TULUM" },
  { zone: "RM", name: "BAHIA PRINCIPE COBA" },
  { zone: "RM", name: "BAHIA PRINCIPE TEQUILA // BAHIA PRINCIPE PREMIER" },
  { zone: "RM", name: "BAHIA PRINCIPE AKUMAL" },
  { zone: "RM", name: "BAHIA PRINCIPE SIAN KAAN" },
  { zone: "TULUM", name: "CONRAD TULUM RIVIERA" },
  { zone: "TULUM", name: "HILTON TULUM" },
  { zone: "RM", name: "CASA TORTUGA" },
  { zone: "TULUM", name: "DREAMS TULUM" },
  { zone: "TULUM", name: "SUPER AKI TULUM" },
  { zone: "TULUM", name: "LETRAS TULUM" },
  { zone: "TULUM", name: "THE BEACH TULUM HOTEL" },
  { zone: "TULUM", name: "COPAL TULUM" },
  { zone: "RM", name: "CASA DON REY" },
  { zone: "TULUM", name: "PAPAYA PLAYA PROJECT TULUM" },
  { zone: "TULUM", name: "MAHAYANA TULUM" },
  { zone: "TULUM", name: "KORE TULUM" },
  { zone: "CUN", name: "OCEAN ALLURE COSTA MUJERES" },
];

export function pickupPointsByZone(zone: PickupZone) {
  return pickupPoints.filter((p) => p.zone === zone);
}
