/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResenasRouteImport } from './routes/resenas'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as AdminToursIndexRouteImport } from './routes/admin.tours.index'
import { Route as AdminToursSlugRouteImport } from './routes/admin.tours.$slug'
import { Route as AdminToursNewRouteImport } from './routes/admin.tours.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResenasRoute = ResenasRouteImport.update({
  id: '/resenas',
  path: '/resenas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const AdminToursIndexRoute = AdminToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursSlugRoute = AdminToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursNewRoute = AdminToursNewRouteImport.update({
  id: '/tours/new',
  path: '/tours/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/login': typeof LoginRoute
  '/resenas': typeof ResenasRoute
  '/tours': typeof ToursRouteWithChildren
  '/tours/$slug': typeof ToursSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/tours/$slug': typeof AdminToursSlugRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/admin/tours/': typeof AdminToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/login': typeof LoginRoute
  '/resenas': typeof ResenasRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/admin': typeof AdminIndexRoute
  '/tours': typeof ToursIndexRoute
  '/admin/tours/$slug': typeof AdminToursSlugRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/admin/tours': typeof AdminToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/login': typeof LoginRoute
  '/resenas': typeof ResenasRoute
  '/tours': typeof ToursRouteWithChildren
  '/tours/$slug': typeof ToursSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/tours/$slug': typeof AdminToursSlugRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/admin/tours/': typeof AdminToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/confirmacion'
    | '/login'
    | '/resenas'
    | '/tours'
    | '/tours/$slug'
    | '/admin/'
    | '/tours/'
    | '/admin/tours/$slug'
    | '/admin/tours/new'
    | '/admin/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confirmacion'
    | '/login'
    | '/resenas'
    | '/tours/$slug'
    | '/admin'
    | '/tours'
    | '/admin/tours/$slug'
    | '/admin/tours/new'
    | '/admin/tours'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/confirmacion'
    | '/login'
    | '/resenas'
    | '/tours'
    | '/tours/$slug'
    | '/admin/'
    | '/tours/'
    | '/admin/tours/$slug'
    | '/admin/tours/new'
    | '/admin/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  LoginRoute: typeof LoginRoute
  ResenasRoute: typeof ResenasRoute
  ToursRoute: typeof ToursRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resenas': {
      id: '/resenas'
      path: '/resenas'
      fullPath: '/resenas'
      preLoaderRoute: typeof ResenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/admin/tours/': {
      id: '/admin/tours/'
      path: '/tours'
      fullPath: '/admin/tours/'
      preLoaderRoute: typeof AdminToursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours/$slug': {
      id: '/admin/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/admin/tours/$slug'
      preLoaderRoute: typeof AdminToursSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours/new': {
      id: '/admin/tours/new'
      path: '/tours/new'
      fullPath: '/admin/tours/new'
      preLoaderRoute: typeof AdminToursNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminToursSlugRoute: typeof AdminToursSlugRoute
  AdminToursNewRoute: typeof AdminToursNewRoute
  AdminToursIndexRoute: typeof AdminToursIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminToursSlugRoute: AdminToursSlugRoute,
  AdminToursNewRoute: AdminToursNewRoute,
  AdminToursIndexRoute: AdminToursIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  LoginRoute: LoginRoute,
  ResenasRoute: ResenasRoute,
  ToursRoute: ToursRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
